[package]
name = "dashboard"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.3.2", features = ["full"] }
dotenv = "0.15.0"
eyre = "0.6.12"
futures-util = "0.3.30"
tokio = { version = "1.40.0", features = ["full"] }
